// go generate
// FILE GENERATO AUTOMATICAMENTE; NON MODIFICARE
// Generato il:
// 2017-05-28 11:51:55.7483513 +0200 CEST
// usando dati scaricati da:
// http://www.salute.gov.it/imgs/C_17_pubblicazioni_1055_ulterioriallegati_ulterioreallegato_0_alleg.txt

package generacodicefiscale

// Nazionecodice : array con il codice istat della nazione ed i relativi codici ISO
type Nazionecodice struct {
	Codice, Nazione, CodiceISO, CodiceISO3 string
}

// Nazionecod : codici nazione
var Nazionecod = []Nazionecodice{
	{Codice: "Z301", Nazione: "Afghanistan", CodiceISO: "AF", CodiceISO3: "AFG"},
	{Codice: "Z201", Nazione: "Albania", CodiceISO: "AL", CodiceISO3: "ALB"},
	{Codice: "Z401", Nazione: "Algeria", CodiceISO: "DZ", CodiceISO3: "DZA"},
	{Codice: "Z202", Nazione: "Andorra", CodiceISO: "AD", CodiceISO3: "AND"},
	{Codice: "Z402", Nazione: "Angola", CodiceISO: "AO", CodiceISO3: "AGO"},
	{Codice: "Z502", Nazione: "Anguilla", CodiceISO: "AI", CodiceISO3: "AIA"},
	{Codice: "Z503", Nazione: "Antigua e Barbuda", CodiceISO: "AG", CodiceISO3: "ATG"},
	{Codice: "Z302", Nazione: "Arabia Saudita", CodiceISO: "SA", CodiceISO3: "SAU"},
	{Codice: "Z602", Nazione: "Argentina", CodiceISO: "AR", CodiceISO3: "ARG"},
	{Codice: "Z358", Nazione: "Armenia", CodiceISO: "AM", CodiceISO3: "ARM"},
	{Codice: "Z603", Nazione: "Aruba", CodiceISO: "AW", CodiceISO3: "ABW"},
	{Codice: "Z701", Nazione: "Australia", CodiceISO: "AU", CodiceISO3: "AUS"},
	{Codice: "Z203", Nazione: "Austria", CodiceISO: "AT", CodiceISO3: "AUT"},
	{Codice: "Z359", Nazione: "Azerbaijan", CodiceISO: "AZ", CodiceISO3: "AZE"},
	{Codice: "Z505", Nazione: "Bahamas", CodiceISO: "BS", CodiceISO3: "BHS"},
	{Codice: "Z304", Nazione: "Bahrain", CodiceISO: "BH", CodiceISO3: "BHR"},
	{Codice: "Z305", Nazione: "Bangladesh", CodiceISO: "BD", CodiceISO3: "BGD"},
	{Codice: "Z506", Nazione: "Barbados", CodiceISO: "BB", CodiceISO3: "BRB"},
	{Codice: "Z206", Nazione: "Belgio", CodiceISO: "BE", CodiceISO3: "BEL"},
	{Codice: "Z507", Nazione: "Belize", CodiceISO: "BZ", CodiceISO3: "BLZ"},
	{Codice: "Z406", Nazione: "Benin", CodiceISO: "BJ", CodiceISO3: "BEN"},
	{Codice: "Z508", Nazione: "Bermuda", CodiceISO: "BM", CodiceISO3: "BMU"},
	{Codice: "Z306", Nazione: "Bhutan", CodiceISO: "BT", CodiceISO3: "BTN"},
	{Codice: "Z256", Nazione: "Bielorussia", CodiceISO: "BY", CodiceISO3: "BLR"},
	{Codice: "Z604", Nazione: "Bolivia", CodiceISO: "BO", CodiceISO3: "BOL"},
	{Codice: "Z252", Nazione: "Bosnia Erzegovina", CodiceISO: "BA", CodiceISO3: "BIH"},
	{Codice: "Z408", Nazione: "Botswana", CodiceISO: "BW", CodiceISO3: "BWA"},
	{Codice: "Z605", Nazione: "Brasile", CodiceISO: "BR", CodiceISO3: "BRA"},
	{Codice: "Z309", Nazione: "Brunei Darussalam", CodiceISO: "BN", CodiceISO3: "BRN"},
	{Codice: "Z209", Nazione: "Bulgaria", CodiceISO: "BG", CodiceISO3: "BGR"},
	{Codice: "Z409", Nazione: "Burkina Faso", CodiceISO: "BF", CodiceISO3: "BFA"},
	{Codice: "Z410", Nazione: "Burundi", CodiceISO: "BI", CodiceISO3: "BDI"},
	{Codice: "Z310", Nazione: "Cambogia", CodiceISO: "KH", CodiceISO3: "KHM"},
	{Codice: "Z411", Nazione: "Camerun", CodiceISO: "CM", CodiceISO3: "CMR"},
	{Codice: "Z509", Nazione: "Canada", CodiceISO: "CA", CodiceISO3: "CAN"},
	{Codice: "Z413", Nazione: "Capo Verde", CodiceISO: "CV", CodiceISO3: "CPV"},
	{Codice: "Z415", Nazione: "Ciad", CodiceISO: "TD", CodiceISO3: "TCD"},
	{Codice: "Z606", Nazione: "Cile", CodiceISO: "CL", CodiceISO3: "CHL"},
	{Codice: "Z314", Nazione: "Cina", CodiceISO: "CN", CodiceISO3: "CHN"},
	{Codice: "Z315", Nazione: "Cipro", CodiceISO: "CY", CodiceISO3: "CYP"},
	{Codice: "Z246", Nazione: "Città del Vaticano", CodiceISO: "VA", CodiceISO3: "VAT"},
	{Codice: "Z608", Nazione: "Colombia", CodiceISO: "CO", CodiceISO3: "COL"},
	{Codice: "Z417", Nazione: "Comore", CodiceISO: "KM", CodiceISO3: "COM"},
	{Codice: "Z319", Nazione: "Corea del Nord", CodiceISO: "KP", CodiceISO3: "PRK"},
	{Codice: "Z320", Nazione: "Corea del Sud", CodiceISO: "KR", CodiceISO3: "KOR"},
	{Codice: "Z513", Nazione: "Costa Rica", CodiceISO: "CR", CodiceISO3: "CRI"},
	{Codice: "Z404", Nazione: "Costa d'Avorio", CodiceISO: "CI", CodiceISO3: "CIV"},
	{Codice: "Z250", Nazione: "Croazia", CodiceISO: "HR", CodiceISO3: "HRV"},
	{Codice: "Z514", Nazione: "Cuba", CodiceISO: "CU", CodiceISO3: "CUB"},
	{Codice: "Z212", Nazione: "Danimarca", CodiceISO: "DK", CodiceISO3: "DNK"},
	{Codice: "Z515", Nazione: "Dominica", CodiceISO: "DM", CodiceISO3: "DMA"},
	{Codice: "Z609", Nazione: "Ecuador", CodiceISO: "EC", CodiceISO3: "ECU"},
	{Codice: "Z419", Nazione: "Egitto", CodiceISO: "EG", CodiceISO3: "EGY"},
	{Codice: "Z221", Nazione: "Eire", CodiceISO: "IE", CodiceISO3: "IRL"},
	{Codice: "Z517", Nazione: "El Salvador", CodiceISO: "SV", CodiceISO3: "SLV"},
	{Codice: "Z322", Nazione: "Emirati Arabi Uniti", CodiceISO: "AE", CodiceISO3: "ARE"},
	{Codice: "Z466", Nazione: "Eritrea", CodiceISO: "ER", CodiceISO3: "ERI"},
	{Codice: "Z247", Nazione: "Estonia", CodiceISO: "EE", CodiceISO3: "EST"},
	{Codice: "Z420", Nazione: "Etiopia", CodiceISO: "ET", CodiceISO3: "ETH"},
	{Codice: "Z245", Nazione: "Federazione Russa", CodiceISO: "RU", CodiceISO3: "RUS"},
	{Codice: "Z703", Nazione: "Fiji", CodiceISO: "FJ", CodiceISO3: "FJI"},
	{Codice: "Z323", Nazione: "Filippine", CodiceISO: "PH", CodiceISO3: "PHL"},
	{Codice: "Z214", Nazione: "Finlandia", CodiceISO: "FI", CodiceISO3: "FIN"},
	{Codice: "Z215", Nazione: "Francia", CodiceISO: "FR", CodiceISO3: "FRA"},
	{Codice: "Z421", Nazione: "Gabon", CodiceISO: "GA", CodiceISO3: "GAB"},
	{Codice: "Z422", Nazione: "Gambia", CodiceISO: "GM", CodiceISO3: "GMB"},
	{Codice: "Z360", Nazione: "Georgia", CodiceISO: "GE", CodiceISO3: "GEO"},
	{Codice: "Z216", Nazione: "Germania", CodiceISO: "DE", CodiceISO3: "DEU"},
	{Codice: "Z423", Nazione: "Ghana", CodiceISO: "GH", CodiceISO3: "GHA"},
	{Codice: "Z518", Nazione: "Giamaica", CodiceISO: "JM", CodiceISO3: "JAM"},
	{Codice: "Z326", Nazione: "Giappone", CodiceISO: "JP", CodiceISO3: "JPN"},
	{Codice: "Z424", Nazione: "Gibuti", CodiceISO: "DJ", CodiceISO3: "DJI"},
	{Codice: "Z327", Nazione: "Giordania", CodiceISO: "JO", CodiceISO3: "JOR"},
	{Codice: "Z220", Nazione: "Grecia", CodiceISO: "GR", CodiceISO3: "GRC"},
	{Codice: "Z519", Nazione: "Grenada", CodiceISO: "GD", CodiceISO3: "GRD"},
	{Codice: "Z523", Nazione: "Guatemala", CodiceISO: "GT", CodiceISO3: "GTM"},
	{Codice: "Z831", Nazione: "Guernsey", CodiceISO: "GG", CodiceISO3: "GGY"},
	{Codice: "Z425", Nazione: "Guinea", CodiceISO: "GN", CodiceISO3: "GIN"},
	{Codice: "Z427", Nazione: "Guinea Equatoriale", CodiceISO: "GQ", CodiceISO3: "GNQ"},
	{Codice: "Z426", Nazione: "Guinea-Bissau", CodiceISO: "GW", CodiceISO3: "GNB"},
	{Codice: "Z612", Nazione: "Guyana", CodiceISO: "GY", CodiceISO3: "GUY"},
	{Codice: "Z524", Nazione: "Haiti", CodiceISO: "HT", CodiceISO3: "HTI"},
	{Codice: "Z525", Nazione: "Honduras", CodiceISO: "HN", CodiceISO3: "HND"},
	{Codice: "Z330", Nazione: "India", CodiceISO: "IN", CodiceISO3: "IND"},
	{Codice: "Z331", Nazione: "Indonesia", CodiceISO: "ID", CodiceISO3: "IDN"},
	{Codice: "Z332", Nazione: "Iran", CodiceISO: "IR", CodiceISO3: "IRN"},
	{Codice: "Z333", Nazione: "Iraq", CodiceISO: "IQ", CodiceISO3: "IRQ"},
	{Codice: "Z223", Nazione: "Islanda", CodiceISO: "IS", CodiceISO3: "ISL"},
	{Codice: "Z712", Nazione: "Isole Marshall", CodiceISO: "MH", CodiceISO3: "MHL"},
	{Codice: "Z725", Nazione: "Isole Solomon", CodiceISO: "SB", CodiceISO3: "SLB"},
	{Codice: "Z334", Nazione: "Israele", CodiceISO: "IL", CodiceISO3: "ISR"},
	{Codice: "Z356", Nazione: "Kazakhistan", CodiceISO: "KZ", CodiceISO3: "KAZ"},
	{Codice: "Z428", Nazione: "Kenya", CodiceISO: "KE", CodiceISO3: "KEN"},
	{Codice: "Z361", Nazione: "Kirghizistan", CodiceISO: "KG", CodiceISO3: "KGZ"},
	{Codice: "Z708", Nazione: "Kiribati", CodiceISO: "KI", CodiceISO3: "KIR"},
	{Codice: "Z335", Nazione: "Kuwait", CodiceISO: "KW", CodiceISO3: "KWT"},
	{Codice: "Z336", Nazione: "Laos", CodiceISO: "LA", CodiceISO3: "LAO"},
	{Codice: "Z429", Nazione: "Lesotho", CodiceISO: "LS", CodiceISO3: "LSO"},
	{Codice: "Z248", Nazione: "Lettonia", CodiceISO: "LV", CodiceISO3: "LVA"},
	{Codice: "Z337", Nazione: "Libano", CodiceISO: "LB", CodiceISO3: "LBN"},
	{Codice: "Z430", Nazione: "Liberia", CodiceISO: "LR", CodiceISO3: "LBR"},
	{Codice: "Z431", Nazione: "Libia", CodiceISO: "LY", CodiceISO3: "LBY"},
	{Codice: "Z225", Nazione: "Liechtenstein", CodiceISO: "LI", CodiceISO3: "LIE"},
	{Codice: "Z249", Nazione: "Lituania", CodiceISO: "LT", CodiceISO3: "LTU"},
	{Codice: "Z226", Nazione: "Lussemburgo", CodiceISO: "LU", CodiceISO3: "LUX"},
	{Codice: "Z253", Nazione: "Macedonia", CodiceISO: "MK", CodiceISO3: "MKD"},
	{Codice: "Z432", Nazione: "Madagascar", CodiceISO: "MG", CodiceISO3: "MDG"},
	{Codice: "Z434", Nazione: "Malawi", CodiceISO: "MW", CodiceISO3: "MWI"},
	{Codice: "Z339", Nazione: "Maldive", CodiceISO: "MV", CodiceISO3: "MDV"},
	{Codice: "Z340", Nazione: "Malesia", CodiceISO: "MY", CodiceISO3: "MYS"},
	{Codice: "Z435", Nazione: "Mali", CodiceISO: "ML", CodiceISO3: "MLI"},
	{Codice: "Z227", Nazione: "Malta", CodiceISO: "MT", CodiceISO3: "MLT"},
	{Codice: "Z436", Nazione: "Marocco", CodiceISO: "MA", CodiceISO3: "MAR"},
	{Codice: "Z437", Nazione: "Mauritania", CodiceISO: "MR", CodiceISO3: "MRT"},
	{Codice: "Z438", Nazione: "Maurizius", CodiceISO: "MU", CodiceISO3: "MUS"},
	{Codice: "Z527", Nazione: "Messico", CodiceISO: "MX", CodiceISO3: "MEX"},
	{Codice: "Z254", Nazione: "Moldavia", CodiceISO: "MD", CodiceISO3: "MDA"},
	{Codice: "Z229", Nazione: "Monaco", CodiceISO: "MC", CodiceISO3: "MCO"},
	{Codice: "Z3412", Nazione: "Mongolia", CodiceISO: "MN", CodiceISO3: "MNG"},
	{Codice: "Z270", Nazione: "Montenegro", CodiceISO: "ME", CodiceISO3: "MNE"},
	{Codice: "Z440", Nazione: "Mozambico", CodiceISO: "MZ", CodiceISO3: "MOZ"},
	{Codice: "Z307", Nazione: "Myanmar", CodiceISO: "MM", CodiceISO3: "MMR"},
	{Codice: "Z441", Nazione: "Namibia", CodiceISO: "NA", CodiceISO3: "NAM"},
	{Codice: "Z715", Nazione: "Nauru", CodiceISO: "NR", CodiceISO3: "NRU"},
	{Codice: "Z342", Nazione: "Nepal", CodiceISO: "NP", CodiceISO3: "NPL"},
	{Codice: "Z529", Nazione: "Nicaragua", CodiceISO: "NI", CodiceISO3: "NIC"},
	{Codice: "Z442", Nazione: "Niger", CodiceISO: "NE", CodiceISO3: "NER"},
	{Codice: "Z443", Nazione: "Nigeria", CodiceISO: "NG", CodiceISO3: "NGA"},
	{Codice: "Z231", Nazione: "Norvegia", CodiceISO: "NO", CodiceISO3: "NOR"},
	{Codice: "Z719", Nazione: "Nuova Zelanda", CodiceISO: "NZ", CodiceISO3: "NZL"},
	{Codice: "Z343", Nazione: "Oman", CodiceISO: "OM", CodiceISO3: "OMN"},
	{Codice: "Z232", Nazione: "Paesi Bassi", CodiceISO: "NL", CodiceISO3: "NLD"},
	{Codice: "Z344", Nazione: "Pakistan", CodiceISO: "PK", CodiceISO3: "PAK"},
	{Codice: "Z720", Nazione: "Palau", CodiceISO: "PW", CodiceISO3: "PLW"},
	{Codice: "Z530", Nazione: "Panamá", CodiceISO: "PA", CodiceISO3: "PAN"},
	{Codice: "Z721", Nazione: "Papua Nuova Guinea", CodiceISO: "PG", CodiceISO3: "PNG"},
	{Codice: "Z614", Nazione: "Paraguay", CodiceISO: "PY", CodiceISO3: "PRY"},
	{Codice: "Z615", Nazione: "Peru", CodiceISO: "PE", CodiceISO3: "PER"},
	{Codice: "Z233", Nazione: "Polonia", CodiceISO: "PL", CodiceISO3: "POL"},
	{Codice: "Z234", Nazione: "Portogallo", CodiceISO: "PT", CodiceISO3: "PRT"},
	{Codice: "Z345", Nazione: "Qatar", CodiceISO: "QA", CodiceISO3: "QAT"},
	{Codice: "Z219", Nazione: "Regno Unito", CodiceISO: "GB", CodiceISO3: "GBR"},
	{Codice: "Z257", Nazione: "Repubblica Ceca", CodiceISO: "CZ", CodiceISO3: "CZE"},
	{Codice: "Z414", Nazione: "Repubblica Centroafricana", CodiceISO: "CF", CodiceISO3: "CAF"},
	{Codice: "Z463", Nazione: "Repubblica Democratica del Congo", CodiceISO: "CD", CodiceISO3: "COD"},
	{Codice: "Z516", Nazione: "Repubblica Dominicana", CodiceISO: "DO", CodiceISO3: "DOM"},
	{Codice: "Z418", Nazione: "Repubblica del Congo", CodiceISO: "CG", CodiceISO3: "COG"},
	{Codice: "Z235", Nazione: "Romania", CodiceISO: "RO", CodiceISO3: "ROU"},
	{Codice: "Z446", Nazione: "Ruanda", CodiceISO: "RW", CodiceISO3: "RWA"},
	{Codice: "Z534", Nazione: "Saint Kitts e Nevis", CodiceISO: "KN", CodiceISO3: "KNA"},
	{Codice: "Z533", Nazione: "Saint Vincent e Grenadine", CodiceISO: "VC", CodiceISO3: "VCT"},
	{Codice: "Z727", Nazione: "Samoa", CodiceISO: "WS", CodiceISO3: "WSM"},
	{Codice: "Z236", Nazione: "San Marino", CodiceISO: "SM", CodiceISO3: "SMR"},
	{Codice: "Z532", Nazione: "Santa Lucia", CodiceISO: "LC", CodiceISO3: "LCA"},
	{Codice: "Z448", Nazione: "Sao Tome e Principe", CodiceISO: "ST", CodiceISO3: "STP"},
	{Codice: "Z450", Nazione: "Senegal", CodiceISO: "SN", CodiceISO3: "SEN"},
	{Codice: "Z449", Nazione: "Seychelles", CodiceISO: "SC", CodiceISO3: "SYC"},
	{Codice: "Z451", Nazione: "Sierra Leone", CodiceISO: "SL", CodiceISO3: "SLE"},
	{Codice: "Z346", Nazione: "Singapore", CodiceISO: "SG", CodiceISO3: "SGP"},
	{Codice: "Z348", Nazione: "Siria", CodiceISO: "SY", CodiceISO3: "SYR"},
	{Codice: "Z255", Nazione: "Slovacchia", CodiceISO: "SK", CodiceISO3: "SVK"},
	{Codice: "Z251", Nazione: "Slovenia", CodiceISO: "SI", CodiceISO3: "SVN"},
	{Codice: "Z453", Nazione: "Somalia", CodiceISO: "SO", CodiceISO3: "SOM"},
	{Codice: "Z239", Nazione: "Spagna", CodiceISO: "ES", CodiceISO3: "ESP"},
	{Codice: "Z311", Nazione: "Sri Lanka", CodiceISO: "LK", CodiceISO3: "LKA"},
	{Codice: "Z713", Nazione: "Stati Federati della Micronesia", CodiceISO: "FM", CodiceISO3: "FSM"},
	{Codice: "Z536", Nazione: "Stati Uniti d'America", CodiceISO: "US", CodiceISO3: "USA"},
	{Codice: "Z454", Nazione: "Sud Africa", CodiceISO: "ZA", CodiceISO3: "ZAF"},
	{Codice: "Z360", Nazione: "Sud Georgia e Isole Sandwich", CodiceISO: "GS", CodiceISO3: "SGS"},
	{Codice: "Z455", Nazione: "Sudan", CodiceISO: "SD", CodiceISO3: "SDN"},
	{Codice: "Z616", Nazione: "Suriname", CodiceISO: "SR", CodiceISO3: "SUR"},
	{Codice: "Z240", Nazione: "Svezia", CodiceISO: "SE", CodiceISO3: "SWE"},
	{Codice: "Z241", Nazione: "Svizzera", CodiceISO: "CH", CodiceISO3: "CHE"},
	{Codice: "Z456", Nazione: "Swaziland", CodiceISO: "SZ", CodiceISO3: "SWZ"},
	{Codice: "Z362", Nazione: "Tagikistan", CodiceISO: "TJ", CodiceISO3: "TJK"},
	{Codice: "Z349", Nazione: "Tailandia", CodiceISO: "TH", CodiceISO3: "THA"},
	{Codice: "Z363", Nazione: "Taiwan", CodiceISO: "TW", CodiceISO3: "TWN"},
	{Codice: "Z457", Nazione: "Tanzania", CodiceISO: "TZ", CodiceISO3: "TZA"},
	{Codice: "Z324", Nazione: "Territori Palestinesi Occupati", CodiceISO: "PS", CodiceISO3: "PSE"},
	{Codice: "Z338", Nazione: "Timor Est", CodiceISO: "TL", CodiceISO3: "TLS"},
	{Codice: "Z458", Nazione: "Togo", CodiceISO: "TG", CodiceISO3: "TGO"},
	{Codice: "Z730", Nazione: "Tonga", CodiceISO: "TO", CodiceISO3: "TON"},
	{Codice: "Z617", Nazione: "Trinidad e Tobago", CodiceISO: "TT", CodiceISO3: "TTO"},
	{Codice: "Z460", Nazione: "Tunisia", CodiceISO: "TN", CodiceISO3: "TUN"},
	{Codice: "Z351", Nazione: "Turchia", CodiceISO: "TR", CodiceISO3: "TUR"},
	{Codice: "Z364", Nazione: "Turkmenistan", CodiceISO: "TM", CodiceISO3: "TKM"},
	{Codice: "Z731", Nazione: "Tuvalu", CodiceISO: "TV", CodiceISO3: "TUV"},
	{Codice: "Z243", Nazione: "Ucraina", CodiceISO: "UA", CodiceISO3: "UKR"},
	{Codice: "Z461", Nazione: "Uganda", CodiceISO: "UG", CodiceISO3: "UGA"},
	{Codice: "Z244", Nazione: "Ungheria", CodiceISO: "HU", CodiceISO3: "HUN"},
	{Codice: "Z618", Nazione: "Uruguay", CodiceISO: "UY", CodiceISO3: "URY"},
	{Codice: "Z357", Nazione: "Uzbekistan", CodiceISO: "UZ", CodiceISO3: "UZB"},
	{Codice: "Z732", Nazione: "Vanuatu", CodiceISO: "VU", CodiceISO3: "VUT"},
	{Codice: "Z619", Nazione: "Venezuela", CodiceISO: "VE", CodiceISO3: "VEN"},
	{Codice: "Z353", Nazione: "Vietnam", CodiceISO: "VN", CodiceISO3: "VNM"},
	{Codice: "Z354", Nazione: "Yemen", CodiceISO: "YE", CodiceISO3: "YEM"},
	{Codice: "Z464", Nazione: "Zambia", CodiceISO: "ZM", CodiceISO3: "ZMB"},
	{Codice: "Z465", Nazione: "Zimbabwe", CodiceISO: "ZW", CodiceISO3: "ZWE"},
}
