// go generate
// FILE GENERATO AUTOMATICAMENTE; NON MODIFICARE
// Generato il:
// 2023-04-25 21:17:25.1548053 +0200 CEST m=+0.747554001
// usando dati scaricati da:
// https://www.istat.it/it/files//2011/01/Elenco-codici-e-denominazioni-unita-territoriali-estere.zip

package generacodicefiscale

// Nazionecodice : array con il codice istat della nazione ed i relativi codici ISO
type Nazionecodice struct {
	Codice, Nazione, CodiceISO, CodiceISO3 string
}

// Nazionecod : array con i dati, nazione per nazione
var Nazionecod = []Nazionecodice{
	{Codice: "Z200", Nazione: "Afghanistan", CodiceISO: "AF", CodiceISO3: "AFG"},
	{Codice: "Z100", Nazione: "Albania", CodiceISO: "AL", CodiceISO3: "ALB"},
	{Codice: "Z301", Nazione: "Algeria", CodiceISO: "DZ", CodiceISO3: "DZA"},
	{Codice: "Z101", Nazione: "Andorra", CodiceISO: "AD", CodiceISO3: "AND"},
	{Codice: "Z302", Nazione: "Angola", CodiceISO: "AO", CodiceISO3: "AGO"},
	{Codice: "Z529", Nazione: "Anguilla", CodiceISO: "AI", CodiceISO3: "AIA"},
	{Codice: "Z532", Nazione: "Antigua e Barbuda", CodiceISO: "AG", CodiceISO3: "ATG"},
	{Codice: "Z203", Nazione: "Arabia Saudita", CodiceISO: "SA", CodiceISO3: "SAU"},
	{Codice: "Z600", Nazione: "Argentina", CodiceISO: "AR", CodiceISO3: "ARG"},
	{Codice: "Z252", Nazione: "Armenia", CodiceISO: "AM", CodiceISO3: "ARM"},
	{Codice: "Z501", Nazione: "Aruba", CodiceISO: "AW", CodiceISO3: "ABW"},
	{Codice: "Z700", Nazione: "Australia", CodiceISO: "AU", CodiceISO3: "AUS"},
	{Codice: "Z102", Nazione: "Austria", CodiceISO: "AT", CodiceISO3: "AUT"},
	{Codice: "Z253", Nazione: "Azerbaigian", CodiceISO: "AZ", CodiceISO3: "AZE"},
	{Codice: "Z502", Nazione: "Bahamas", CodiceISO: "BS", CodiceISO3: "BHS"},
	{Codice: "Z204", Nazione: "Bahrein", CodiceISO: "BH", CodiceISO3: "BHR"},
	{Codice: "Z249", Nazione: "Bangladesh", CodiceISO: "BD", CodiceISO3: "BGD"},
	{Codice: "Z522", Nazione: "Barbados", CodiceISO: "BB", CodiceISO3: "BRB"},
	{Codice: "Z103", Nazione: "Belgio", CodiceISO: "BE", CodiceISO3: "BEL"},
	{Codice: "Z512", Nazione: "Belize", CodiceISO: "BZ", CodiceISO3: "BLZ"},
	{Codice: "Z314", Nazione: "Benin", CodiceISO: "BJ", CodiceISO3: "BEN"},
	{Codice: "Z400", Nazione: "Bermuda", CodiceISO: "BM", CodiceISO3: "BMU"},
	{Codice: "Z205", Nazione: "Bhutan", CodiceISO: "BT", CodiceISO3: "BTN"},
	{Codice: "Z139", Nazione: "Bielorussia", CodiceISO: "BY", CodiceISO3: "BLR"},
	{Codice: "Z601", Nazione: "Bolivia", CodiceISO: "BO", CodiceISO3: "BOL"},
	{Codice: "Z153", Nazione: "Bosnia-Erzegovina", CodiceISO: "BA", CodiceISO3: "BIH"},
	{Codice: "Z358", Nazione: "Botswana", CodiceISO: "BW", CodiceISO3: "BWA"},
	{Codice: "Z602", Nazione: "Brasile", CodiceISO: "BR", CodiceISO3: "BRA"},
	{Codice: "Z207", Nazione: "Brunei Darussalam", CodiceISO: "BN", CodiceISO3: "BRN"},
	{Codice: "Z104", Nazione: "Bulgaria", CodiceISO: "BG", CodiceISO3: "BGR"},
	{Codice: "Z354", Nazione: "Burkina Faso", CodiceISO: "BF", CodiceISO3: "BFA"},
	{Codice: "Z305", Nazione: "Burundi", CodiceISO: "BI", CodiceISO3: "BDI"},
	{Codice: "Z208", Nazione: "Cambogia", CodiceISO: "KH", CodiceISO3: "KHM"},
	{Codice: "Z306", Nazione: "Camerun", CodiceISO: "CM", CodiceISO3: "CMR"},
	{Codice: "Z401", Nazione: "Canada", CodiceISO: "CA", CodiceISO3: "CAN"},
	{Codice: "Z307", Nazione: "Capo Verde", CodiceISO: "CV", CodiceISO3: "CPV"},
	{Codice: "Z309", Nazione: "Ciad", CodiceISO: "TD", CodiceISO3: "TCD"},
	{Codice: "Z603", Nazione: "Cile", CodiceISO: "CL", CodiceISO3: "CHL"},
	{Codice: "Z210", Nazione: "Cina", CodiceISO: "CN", CodiceISO3: "CHN"},
	{Codice: "Z211", Nazione: "Cipro", CodiceISO: "CY", CodiceISO3: "CYP"},
	{Codice: "Z604", Nazione: "Colombia", CodiceISO: "CO", CodiceISO3: "COL"},
	{Codice: "Z310", Nazione: "Comore", CodiceISO: "KM", CodiceISO3: "COM"},
	{Codice: "Z311", Nazione: "Congo", CodiceISO: "CG", CodiceISO3: "COG"},
	{Codice: "Z214", Nazione: "Corea del Nord", CodiceISO: "KP", CodiceISO3: "PRK"},
	{Codice: "Z213", Nazione: "Corea del Sud", CodiceISO: "KR", CodiceISO3: "KOR"},
	{Codice: "Z503", Nazione: "Costa Rica", CodiceISO: "CR", CodiceISO3: "CRI"},
	{Codice: "Z313", Nazione: "Costa d'Avorio", CodiceISO: "CI", CodiceISO3: "CIV"},
	{Codice: "Z149", Nazione: "Croazia", CodiceISO: "HR", CodiceISO3: "HRV"},
	{Codice: "Z504", Nazione: "Cuba", CodiceISO: "CU", CodiceISO3: "CUB"},
	{Codice: "Z107", Nazione: "Danimarca", CodiceISO: "DK", CodiceISO3: "DNK"},
	{Codice: "Z526", Nazione: "Dominica", CodiceISO: "DM", CodiceISO3: "DMA"},
	{Codice: "Z605", Nazione: "Ecuador", CodiceISO: "EC", CodiceISO3: "ECU"},
	{Codice: "Z336", Nazione: "Egitto", CodiceISO: "EG", CodiceISO3: "EGY"},
	{Codice: "Z506", Nazione: "El Salvador", CodiceISO: "SV", CodiceISO3: "SLV"},
	{Codice: "Z215", Nazione: "Emirati Arabi Uniti", CodiceISO: "AE", CodiceISO3: "ARE"},
	{Codice: "Z368", Nazione: "Eritrea", CodiceISO: "ER", CodiceISO3: "ERI"},
	{Codice: "Z144", Nazione: "Estonia", CodiceISO: "EE", CodiceISO3: "EST"},
	{Codice: "Z349", Nazione: "Eswatini", CodiceISO: "SZ", CodiceISO3: "SWZ"},
	{Codice: "Z315", Nazione: "Etiopia", CodiceISO: "ET", CodiceISO3: "ETH"},
	{Codice: "Z154", Nazione: "Federazione russa", CodiceISO: "RU", CodiceISO3: "RUS"},
	{Codice: "Z704", Nazione: "Figi", CodiceISO: "FJ", CodiceISO3: "FJI"},
	{Codice: "Z216", Nazione: "Filippine", CodiceISO: "PH", CodiceISO3: "PHL"},
	{Codice: "Z109", Nazione: "Finlandia", CodiceISO: "FI", CodiceISO3: "FIN"},
	{Codice: "Z110", Nazione: "Francia", CodiceISO: "FR", CodiceISO3: "FRA"},
	{Codice: "Z316", Nazione: "Gabon", CodiceISO: "GA", CodiceISO3: "GAB"},
	{Codice: "Z317", Nazione: "Gambia", CodiceISO: "GM", CodiceISO3: "GMB"},
	{Codice: "Z254", Nazione: "Georgia", CodiceISO: "GE", CodiceISO3: "GEO"},
	{Codice: "Z112", Nazione: "Germania", CodiceISO: "DE", CodiceISO3: "DEU"},
	{Codice: "Z318", Nazione: "Ghana", CodiceISO: "GH", CodiceISO3: "GHA"},
	{Codice: "Z507", Nazione: "Giamaica", CodiceISO: "JM", CodiceISO3: "JAM"},
	{Codice: "Z219", Nazione: "Giappone", CodiceISO: "JP", CodiceISO3: "JPN"},
	{Codice: "Z113", Nazione: "Gibilterra", CodiceISO: "GI", CodiceISO3: "GIB"},
	{Codice: "Z361", Nazione: "Gibuti", CodiceISO: "DJ", CodiceISO3: "DJI"},
	{Codice: "Z220", Nazione: "Giordania", CodiceISO: "JO", CodiceISO3: "JOR"},
	{Codice: "Z115", Nazione: "Grecia", CodiceISO: "GR", CodiceISO3: "GRC"},
	{Codice: "Z524", Nazione: "Grenada", CodiceISO: "GD", CodiceISO3: "GRD"},
	{Codice: "Z402", Nazione: "Groenlandia", CodiceISO: "GL", CodiceISO3: "GRL"},
	{Codice: "Z509", Nazione: "Guatemala", CodiceISO: "GT", CodiceISO3: "GTM"},
	{Codice: "Z319", Nazione: "Guinea", CodiceISO: "GN", CodiceISO3: "GIN"},
	{Codice: "Z321", Nazione: "Guinea equatoriale", CodiceISO: "GQ", CodiceISO3: "GNQ"},
	{Codice: "Z320", Nazione: "Guinea-Bissau", CodiceISO: "GW", CodiceISO3: "GNB"},
	{Codice: "Z606", Nazione: "Guyana", CodiceISO: "GY", CodiceISO3: "GUY"},
	{Codice: "Z510", Nazione: "Haiti", CodiceISO: "HT", CodiceISO3: "HTI"},
	{Codice: "Z511", Nazione: "Honduras", CodiceISO: "HN", CodiceISO3: "HND"},
	{Codice: "Z222", Nazione: "India", CodiceISO: "IN", CodiceISO3: "IND"},
	{Codice: "Z223", Nazione: "Indonesia", CodiceISO: "ID", CodiceISO3: "IDN"},
	{Codice: "Z224", Nazione: "Iran", CodiceISO: "IR", CodiceISO3: "IRN"},
	{Codice: "Z225", Nazione: "Iraq", CodiceISO: "IQ", CodiceISO3: "IRQ"},
	{Codice: "Z116", Nazione: "Irlanda", CodiceISO: "IE", CodiceISO3: "IRL"},
	{Codice: "Z117", Nazione: "Islanda", CodiceISO: "IS", CodiceISO3: "ISL"},
	{Codice: "Z122", Nazione: "Isola di Man", CodiceISO: "IM", CodiceISO3: "IMN"},
	{Codice: "Z530", Nazione: "Isole Cayman", CodiceISO: "KY", CodiceISO3: "CYM"},
	{Codice: "Z703", Nazione: "Isole Cook (NZ)", CodiceISO: "CK", CodiceISO3: "COK"},
	{Codice: "Z609", Nazione: "Isole Falkland (Malvine)", CodiceISO: "FK", CodiceISO3: "FLK"},
	{Codice: "Z108", Nazione: "Isole Fær Øer", CodiceISO: "FO", CodiceISO3: "FRO"},
	{Codice: "Z711", Nazione: "Isole Marshall", CodiceISO: "MH", CodiceISO3: "MHL"},
	{Codice: "Z722", Nazione: "Isole Pitcairn", CodiceISO: "PN", CodiceISO3: "PCN"},
	{Codice: "Z724", Nazione: "Isole Salomone", CodiceISO: "SB", CodiceISO3: "SLB"},
	{Codice: "Z519", Nazione: "Isole Turks e Caicos", CodiceISO: "TC", CodiceISO3: "TCA"},
	{Codice: "Z525", Nazione: "Isole Vergini britanniche", CodiceISO: "VG", CodiceISO3: "VGB"},
	{Codice: "Z226", Nazione: "Israele", CodiceISO: "IL", CodiceISO3: "ISR"},
	{Codice: "Z255", Nazione: "Kazakhstan", CodiceISO: "KZ", CodiceISO3: "KAZ"},
	{Codice: "Z322", Nazione: "Kenya", CodiceISO: "KE", CodiceISO3: "KEN"},
	{Codice: "Z256", Nazione: "Kirghizistan", CodiceISO: "KG", CodiceISO3: "KGZ"},
	{Codice: "Z731", Nazione: "Kiribati", CodiceISO: "KI", CodiceISO3: "KIR"},
	{Codice: "Z160", Nazione: "Kosovo", CodiceISO: "n.d.", CodiceISO3: "KOS"},
	{Codice: "Z227", Nazione: "Kuwait", CodiceISO: "KW", CodiceISO3: "KWT"},
	{Codice: "Z228", Nazione: "Laos", CodiceISO: "LA", CodiceISO3: "LAO"},
	{Codice: "Z359", Nazione: "Lesotho", CodiceISO: "LS", CodiceISO3: "LSO"},
	{Codice: "Z145", Nazione: "Lettonia", CodiceISO: "LV", CodiceISO3: "LVA"},
	{Codice: "Z229", Nazione: "Libano", CodiceISO: "LB", CodiceISO3: "LBN"},
	{Codice: "Z325", Nazione: "Liberia", CodiceISO: "LR", CodiceISO3: "LBR"},
	{Codice: "Z326", Nazione: "Libia", CodiceISO: "LY", CodiceISO3: "LBY"},
	{Codice: "Z119", Nazione: "Liechtenstein", CodiceISO: "LI", CodiceISO3: "LIE"},
	{Codice: "Z146", Nazione: "Lituania", CodiceISO: "LT", CodiceISO3: "LTU"},
	{Codice: "Z120", Nazione: "Lussemburgo", CodiceISO: "LU", CodiceISO3: "LUX"},
	{Codice: "Z148", Nazione: "Macedonia del Nord", CodiceISO: "MK", CodiceISO3: "MKD"},
	{Codice: "Z327", Nazione: "Madagascar", CodiceISO: "MG", CodiceISO3: "MDG"},
	{Codice: "Z328", Nazione: "Malawi", CodiceISO: "MW", CodiceISO3: "MWI"},
	{Codice: "Z247", Nazione: "Malaysia", CodiceISO: "MY", CodiceISO3: "MYS"},
	{Codice: "Z232", Nazione: "Maldive", CodiceISO: "MV", CodiceISO3: "MDV"},
	{Codice: "Z329", Nazione: "Mali", CodiceISO: "ML", CodiceISO3: "MLI"},
	{Codice: "Z121", Nazione: "Malta", CodiceISO: "MT", CodiceISO3: "MLT"},
	{Codice: "Z330", Nazione: "Marocco", CodiceISO: "MA", CodiceISO3: "MAR"},
	{Codice: "Z331", Nazione: "Mauritania", CodiceISO: "MR", CodiceISO3: "MRT"},
	{Codice: "Z332", Nazione: "Maurizio", CodiceISO: "MU", CodiceISO3: "MUS"},
	{Codice: "Z514", Nazione: "Messico", CodiceISO: "MX", CodiceISO3: "MEX"},
	{Codice: "Z140", Nazione: "Moldova", CodiceISO: "MD", CodiceISO3: "MDA"},
	{Codice: "Z123", Nazione: "Monaco", CodiceISO: "MC", CodiceISO3: "MCO"},
	{Codice: "Z233", Nazione: "Mongolia", CodiceISO: "MN", CodiceISO3: "MNG"},
	{Codice: "Z159", Nazione: "Montenegro", CodiceISO: "ME", CodiceISO3: "MNE"},
	{Codice: "Z531", Nazione: "Montserrat", CodiceISO: "MS", CodiceISO3: "MSR"},
	{Codice: "Z333", Nazione: "Mozambico", CodiceISO: "MZ", CodiceISO3: "MOZ"},
	{Codice: "Z206", Nazione: "Myanmar/Birmania", CodiceISO: "MM", CodiceISO3: "MMR"},
	{Codice: "Z300", Nazione: "Namibia", CodiceISO: "NA", CodiceISO3: "NAM"},
	{Codice: "Z713", Nazione: "Nauru", CodiceISO: "NR", CodiceISO3: "NRU"},
	{Codice: "Z234", Nazione: "Nepal", CodiceISO: "NP", CodiceISO3: "NPL"},
	{Codice: "Z515", Nazione: "Nicaragua", CodiceISO: "NI", CodiceISO3: "NIC"},
	{Codice: "Z334", Nazione: "Niger", CodiceISO: "NE", CodiceISO3: "NER"},
	{Codice: "Z335", Nazione: "Nigeria", CodiceISO: "NG", CodiceISO3: "NGA"},
	{Codice: "Z125", Nazione: "Norvegia", CodiceISO: "NO", CodiceISO3: "NOR"},
	{Codice: "Z716", Nazione: "Nuova Caledonia", CodiceISO: "NC", CodiceISO3: "NCL"},
	{Codice: "Z719", Nazione: "Nuova Zelanda", CodiceISO: "NZ", CodiceISO3: "NZL"},
	{Codice: "Z235", Nazione: "Oman", CodiceISO: "OM", CodiceISO3: "OMN"},
	{Codice: "Z126", Nazione: "Paesi Bassi", CodiceISO: "NL", CodiceISO3: "NLD"},
	{Codice: "Z236", Nazione: "Pakistan", CodiceISO: "PK", CodiceISO3: "PAK"},
	{Codice: "Z734", Nazione: "Palau", CodiceISO: "PW", CodiceISO3: "PLW"},
	{Codice: "Z161", Nazione: "Palestina", CodiceISO: "PS", CodiceISO3: "PSE"},
	{Codice: "Z516", Nazione: "Panama", CodiceISO: "PA", CodiceISO3: "PAN"},
	{Codice: "Z730", Nazione: "Papua Nuova Guinea", CodiceISO: "PG", CodiceISO3: "PNG"},
	{Codice: "Z610", Nazione: "Paraguay", CodiceISO: "PY", CodiceISO3: "PRY"},
	{Codice: "Z611", Nazione: "Perù", CodiceISO: "PE", CodiceISO3: "PER"},
	{Codice: "Z723", Nazione: "Polinesia francese", CodiceISO: "PF", CodiceISO3: "PYF"},
	{Codice: "Z127", Nazione: "Polonia", CodiceISO: "PL", CodiceISO3: "POL"},
	{Codice: "Z128", Nazione: "Portogallo", CodiceISO: "PT", CodiceISO3: "PRT"},
	{Codice: "Z237", Nazione: "Qatar", CodiceISO: "QA", CodiceISO3: "QAT"},
	{Codice: "Z114", Nazione: "Regno Unito", CodiceISO: "UK", CodiceISO3: "GBR"},
	{Codice: "Z308", Nazione: "Repubblica Centrafricana", CodiceISO: "CF", CodiceISO3: "CAF"},
	{Codice: "Z312", Nazione: "Repubblica Democratica del Congo", CodiceISO: "CD", CodiceISO3: "COD"},
	{Codice: "Z505", Nazione: "Repubblica Dominicana", CodiceISO: "DO", CodiceISO3: "DOM"},
	{Codice: "Z156", Nazione: "Repubblica ceca", CodiceISO: "CZ", CodiceISO3: "CZE"},
	{Codice: "Z129", Nazione: "Romania", CodiceISO: "RO", CodiceISO3: "ROU"},
	{Codice: "Z338", Nazione: "Ruanda", CodiceISO: "RW", CodiceISO3: "RWA"},
	{Codice: "Z339", Nazione: "Sahara occidentale", CodiceISO: "EH", CodiceISO3: "ESH"},
	{Codice: "Z533", Nazione: "Saint Kitts e Nevis", CodiceISO: "KN", CodiceISO3: "KNA"},
	{Codice: "Z403", Nazione: "Saint Pierre e Miquelon", CodiceISO: "PM", CodiceISO3: "SPM"},
	{Codice: "Z528", Nazione: "Saint Vincent e Grenadine", CodiceISO: "VC", CodiceISO3: "VCT"},
	{Codice: "Z726", Nazione: "Samoa", CodiceISO: "WS", CodiceISO3: "WSM"},
	{Codice: "Z130", Nazione: "San Marino", CodiceISO: "SM", CodiceISO3: "SMR"},
	{Codice: "Z340", Nazione: "Sant'Elena", CodiceISO: "SH", CodiceISO3: "SHN"},
	{Codice: "Z527", Nazione: "Santa Lucia", CodiceISO: "LC", CodiceISO3: "LCA"},
	{Codice: "Z341", Nazione: "Sao Tomé e Principe", CodiceISO: "ST", CodiceISO3: "STP"},
	{Codice: "Z343", Nazione: "Senegal", CodiceISO: "SN", CodiceISO3: "SEN"},
	{Codice: "Z158", Nazione: "Serbia", CodiceISO: "RS", CodiceISO3: "SRB"},
	{Codice: "Z342", Nazione: "Seychelles", CodiceISO: "SC", CodiceISO3: "SYC"},
	{Codice: "Z344", Nazione: "Sierra Leone", CodiceISO: "SL", CodiceISO3: "SLE"},
	{Codice: "Z248", Nazione: "Singapore", CodiceISO: "SG", CodiceISO3: "SGP"},
	{Codice: "Z240", Nazione: "Siria", CodiceISO: "SY", CodiceISO3: "SYR"},
	{Codice: "Z155", Nazione: "Slovacchia", CodiceISO: "SK", CodiceISO3: "SVK"},
	{Codice: "Z150", Nazione: "Slovenia", CodiceISO: "SI", CodiceISO3: "SVN"},
	{Codice: "Z345", Nazione: "Somalia", CodiceISO: "SO", CodiceISO3: "SOM"},
	{Codice: "Z131", Nazione: "Spagna", CodiceISO: "ES", CodiceISO3: "ESP"},
	{Codice: "Z209", Nazione: "Sri Lanka", CodiceISO: "LK", CodiceISO3: "LKA"},
	{Codice: "Z735", Nazione: "Stati Federati di Micronesia", CodiceISO: "FM", CodiceISO3: "FSM"},
	{Codice: "Z404", Nazione: "Stati Uniti d'America", CodiceISO: "US", CodiceISO3: "USA"},
	{Codice: "Z106", Nazione: "Stato della Città del Vaticano", CodiceISO: "VA", CodiceISO3: "VAT"},
	{Codice: "Z907", Nazione: "Sud Sudan", CodiceISO: "SS", CodiceISO3: "SSD"},
	{Codice: "Z347", Nazione: "Sudafrica", CodiceISO: "ZA", CodiceISO3: "ZAF"},
	{Codice: "Z348", Nazione: "Sudan", CodiceISO: "SD", CodiceISO3: "SDN"},
	{Codice: "Z608", Nazione: "Suriname", CodiceISO: "SR", CodiceISO3: "SUR"},
	{Codice: "Z132", Nazione: "Svezia", CodiceISO: "SE", CodiceISO3: "SWE"},
	{Codice: "Z133", Nazione: "Svizzera", CodiceISO: "CH", CodiceISO3: "CHE"},
	{Codice: "Z257", Nazione: "Tagikistan", CodiceISO: "TJ", CodiceISO3: "TJK"},
	{Codice: "Z217", Nazione: "Taiwan", CodiceISO: "TW", CodiceISO3: "TWN"},
	{Codice: "Z357", Nazione: "Tanzania", CodiceISO: "TZ", CodiceISO3: "TZA"},
	{Codice: "Z241", Nazione: "Thailandia", CodiceISO: "TH", CodiceISO3: "THA"},
	{Codice: "Z242", Nazione: "Timor Leste", CodiceISO: "TL", CodiceISO3: "TLS"},
	{Codice: "Z351", Nazione: "Togo", CodiceISO: "TG", CodiceISO3: "TGO"},
	{Codice: "Z728", Nazione: "Tonga", CodiceISO: "TO", CodiceISO3: "TON"},
	{Codice: "Z612", Nazione: "Trinidad e Tobago", CodiceISO: "TT", CodiceISO3: "TTO"},
	{Codice: "Z352", Nazione: "Tunisia", CodiceISO: "TN", CodiceISO3: "TUN"},
	{Codice: "Z243", Nazione: "Turchia", CodiceISO: "TR", CodiceISO3: "TUR"},
	{Codice: "Z258", Nazione: "Turkmenistan", CodiceISO: "TM", CodiceISO3: "TKM"},
	{Codice: "Z732", Nazione: "Tuvalu", CodiceISO: "TV", CodiceISO3: "TUV"},
	{Codice: "Z138", Nazione: "Ucraina", CodiceISO: "UA", CodiceISO3: "UKR"},
	{Codice: "Z353", Nazione: "Uganda", CodiceISO: "UG", CodiceISO3: "UGA"},
	{Codice: "Z134", Nazione: "Ungheria", CodiceISO: "HU", CodiceISO3: "HUN"},
	{Codice: "Z613", Nazione: "Uruguay", CodiceISO: "UY", CodiceISO3: "URY"},
	{Codice: "Z259", Nazione: "Uzbekistan", CodiceISO: "UZ", CodiceISO3: "UZB"},
	{Codice: "Z733", Nazione: "Vanuatu", CodiceISO: "VU", CodiceISO3: "VUT"},
	{Codice: "Z614", Nazione: "Venezuela", CodiceISO: "VE", CodiceISO3: "VEN"},
	{Codice: "Z251", Nazione: "Vietnam", CodiceISO: "VN", CodiceISO3: "VNM"},
	{Codice: "Z729", Nazione: "Wallis e Futuna", CodiceISO: "WF", CodiceISO3: "WLF"},
	{Codice: "Z246", Nazione: "Yemen", CodiceISO: "YE", CodiceISO3: "YEM"},
	{Codice: "Z355", Nazione: "Zambia", CodiceISO: "ZM", CodiceISO3: "ZMB"},
	{Codice: "Z337", Nazione: "Zimbabwe", CodiceISO: "ZW", CodiceISO3: "ZWE"},
}
